import fs from 'node:fs';
import path from 'node:path';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { buildSync } from 'esbuild';
import {
  LAYOUT_ALIASES,
  LAYOUT_OPTIONS,
  DEFAULT_THEME_PACK,
  THEME_PACK_OPTIONS,
  resolveOption,
} from './options.jsx';
import {
  buildDeckViewModel,
  renderDeckView,
  serializeDeckViewModel,
} from './view-model/index.jsx';
import {
  REQUIRED_OUTPUT_ASSETS,
  RUNTIME_ASSET_PATHS,
  RUNTIME_TEMPLATE,
} from './runtime-assets.mjs';
import {
  buildThemeRegistrySource,
  isFullThemeSet,
  normalizeThemeKeys,
} from './components/themes/theme-registry-codegen.mjs';
import { normalizeDeckLanguage, buildDeckI18nDict } from './i18n.mjs';
import {
  buildClientRuntime,
  buildClientRuntimeFromModules,
  prebuiltBundlePath,
  prebuiltModulePath,
} from './components/themes/runtime-build.mjs';

const ROOT = path.resolve(import.meta.dirname, '..');
const FULL_THEME_REGISTRY = path.join(ROOT, 'src/components/themes/theme-registry.jsx');
const MIGRATION_ONLY_DIRS = new Set(['uploads', 'screens', 'screenshots', 'shots', 'scratch']);

export function renderDeck(deck, { outFile, includeThemeSwitcher = deck.preview?.themeSwitcher === true }) {
  const viewModel = buildDeckViewModel(deck, {
    layouts: LAYOUT_OPTIONS,
    layoutAliases: LAYOUT_ALIASES,
    themePacks: THEME_PACK_OPTIONS,
    defaultThemePack: DEFAULT_THEME_PACK,
    resolveOption,
  });
  const { key: themePackName } = viewModel.themePack;
  const language = normalizeDeckLanguage(deck.language);
  const template = fs.readFileSync(path.join(ROOT, RUNTIME_TEMPLATE), 'utf8');
  const slides = renderToStaticMarkup(<>{renderDeckView(viewModel)}</>);
  let html = insertSlides(template, slides);
  const htmlLang = language === 'en' ? 'en' : 'zh-TW';
  html = html.replace('<html lang="zh-TW">', `<html lang="${htmlLang}" data-theme-pack="${themePackName}">`);
  html = html.replace('<title>[必填] 替換為 PPT 標題 · Deck Title</title>', `<title>${escapeHtml(viewModel.model.title)}</title>`);
  html = injectPreviewOptions(html, viewModel.options, { includeThemeSwitcher, language, viewModel });
  html = injectDeckViewModel(html, serializeDeckViewModel(viewModel));

  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, html);
  copyRuntimeAssets(path.dirname(outFile), { usedThemeKeys: collectUsedThemeKeys(viewModel) });
}

// JAD-201:從 deck 實際用到的主題(每頁 themePack)推導待打包的主題集合。
function collectUsedThemeKeys(viewModel) {
  const keys = new Set();
  for (const slide of viewModel.slides || []) {
    for (const variant of slide.variants || [slide]) {
      if (variant.themePack) keys.add(variant.themePack);
    }
  }
  return normalizeThemeKeys(keys);
}

function insertSlides(template, slides) {
  const startMatch = template.match(/<div id="deck"[^>]*>/);
  const startTag = startMatch?.[0];
  const start = startMatch?.index ?? -1;
  const nav = template.indexOf('<div id="nav"', start);
  const deckEnd = findClosingDiv(template, start);

  if (start === -1 || nav === -1 || deckEnd === -1) {
    throw new Error('Template is missing <div id="deck"> or <div id="nav"> markers.');
  }

  const before = template.slice(0, start + startTag.length);
  const after = template.slice(deckEnd);
  return `${before}\n\n<!-- Generated by scripts/render-deck.jsx -->\n${slides}\n\n${after}`;
}

function findClosingDiv(html, start) {
  if (start < 0) return -1;
  const tagPattern = /<\/?div\b[^>]*>/gi;
  tagPattern.lastIndex = start;
  let depth = 0;
  let match;
  while ((match = tagPattern.exec(html))) {
    if (match[0].startsWith('</')) {
      depth -= 1;
      if (depth === 0) return match.index;
    } else {
      depth += 1;
    }
  }
  return -1;
}

function injectPreviewOptions(html, options, { includeThemeSwitcher = false, language = 'zh', viewModel = null } = {}) {
  const previewOptions = {
    ...options,
    themePacks: includeThemeSwitcher ? options.themePacks : {},
    // 多主題除錯總覽(showcase)不自動儲存:它是共享除錯產物,瀏覽器裡的試驗性編輯
    // 不應燒回 index.html(會汙染 render:themes 與其上執行的其他測試)。
    ...(includeThemeSwitcher ? { autosave: false } : {}),
    language,
    // 詞典子集始終注入(按本 deck 用到的頁面裁剪,通常幾 KB):執行時語言可由
    // 系統語言/使用者手動切換決定,中文 deck 也可能要切到英文介面。
    ...(viewModel ? { i18n: buildDeckI18nDict(viewModel) } : {}),
  };
  const json = escapeScriptJson(JSON.stringify(previewOptions));
  return html.replace(
    /<script id="preview-options" type="application\/json">[\s\S]*?<\/script>/,
    `<script id="preview-options" type="application/json">${json}</script>`,
  );
}

function injectDeckViewModel(html, viewModel) {
  const json = escapeScriptJson(JSON.stringify(viewModel));
  return html.replace(
    /<script id="deck-view-model" type="application\/json">[\s\S]*?<\/script>/,
    `<script id="deck-view-model" type="application/json">${json}</script>`,
  );
}

function copyRuntimeAssets(outDir, { usedThemeKeys = [] } = {}) {
  const assetsDir = path.join(outDir, 'assets');
  const imagesDir = path.join(outDir, 'images');
  for (const dir of [assetsDir, imagesDir]) {
    if (!fs.existsSync(dir)) continue;
    for (const name of fs.readdirSync(dir)) {
      if (name !== 'user-media') fs.rmSync(path.join(dir, name), { recursive: true, force: true });
    }
  }
  [path.join(outDir, 'uploads'), path.join(outDir, 'screens'), path.join(outDir, 'screenshots')].forEach(dir => {
    fs.rmSync(dir, { recursive: true, force: true });
  });
  fs.mkdirSync(assetsDir, { recursive: true });
  copyRequiredFile(path.join(ROOT, 'node_modules/gsap/dist/gsap.min.js'), path.join(assetsDir, 'vendor/gsap.min.js'));
  copyRequiredFile(path.join(ROOT, 'node_modules/pptxgenjs/dist/pptxgen.bundle.js'), path.join(assetsDir, 'vendor/pptxgen.bundle.js'));
  copyRequiredFile(path.join(ROOT, 'node_modules/pdf-lib/dist/pdf-lib.min.js'), path.join(assetsDir, 'vendor/pdf-lib.min.js'));
  copyRequiredFile(path.join(ROOT, 'node_modules/html-to-image/dist/html-to-image.js'), path.join(assetsDir, 'vendor/html-to-image.js'));
  for (const assetPath of RUNTIME_ASSET_PATHS) {
    if (assetPath === RUNTIME_TEMPLATE) continue;
    copyRuntimeAsset(assetPath, outDir);
  }
  copyImportedThemeAssets(outDir, usedThemeKeys);
  buildImportedThemeRuntime(path.join(assetsDir, 'imported-theme-runtime.js'), usedThemeKeys);
  const imageSlotStateFile = path.join(outDir, '.image-slots.state.json');
  if (!fs.existsSync(imageSlotStateFile)) fs.writeFileSync(imageSlotStateFile, '{}\n');
}

function copyRuntimeAsset(assetPath, outDir) {
  const source = path.join(ROOT, assetPath);
  const target = path.join(outDir, assetPath);
  if (!fs.existsSync(source)) {
    throw new Error(`Runtime asset is listed but missing: ${assetPath}`);
  }
  if (fs.statSync(source).isDirectory()) {
    copyDirectoryIfExists(source, target);
  } else {
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.copyFileSync(source, target);
  }
}

// JAD-201/203:打包這份 deck 實際用到主題的瀏覽器執行時。兩條等價路徑(見 runtime-build.mjs):
//   - dev / 有主題源(showcase 全主題、本地迭代):源 esbuild(行為同 JAD-201)。
//   - 安裝版 / 無可讀主題源:單主題複製預構建自包含 bundle;多主題用預構建模組連結。
// `DASHI_PPT_THEME_RUNTIME`:auto(預設,有源走源、無源走預構建)| prebuilt(強制預構建,測試用)
//   | source(強制源)。安裝版無主題源時自動走預構建,產出與源路徑等價(單一 React,水合一致)。
function buildImportedThemeRuntime(outFile, usedThemeKeys = []) {
  const normalized = normalizeThemeKeys(usedThemeKeys || []);
  const mode = process.env.DASHI_PPT_THEME_RUNTIME || 'auto';
  const sourcePresent = hasThemeSource(normalized);
  const wantPrebuilt = mode === 'prebuilt' || (mode === 'auto' && !sourcePresent);

  if (wantPrebuilt) {
    // 單主題(絕大多數 deck):直接複製預構建自包含 bundle —— 零 deck 級 esbuild、零主題源。
    if (normalized.length === 1) {
      const bundle = prebuiltBundlePath(ROOT, normalized[0]);
      if (fs.existsSync(bundle)) {
        fs.copyFileSync(bundle, outFile);
        return;
      }
    }
    // 多主題(或單主題缺自包含 bundle):用預構建 minified 模組連結(無主題源)。
    if (normalized.length && prebuiltModulesAvailable(normalized)) {
      buildClientRuntimeFromModules({ root: ROOT, outFile, themeKeys: normalized });
      return;
    }
    if (mode === 'prebuilt') {
      throw new Error(`prebuilt theme runtime requested but artifacts missing for [${normalized.join(', ')}]; run \`node scripts/build/build-theme-runtime.mjs\`.`);
    }
    // mode=auto 且無源、無預構建:落到下方報錯。
  }

  if (sourcePresent && mode !== 'prebuilt') {
    buildImportedThemeRuntimeFromSource(outFile, normalized);
    return;
  }

  throw new Error(`No imported theme runtime available for [${normalized.join(', ')}] (no readable theme source and no prebuilt artifacts).`);
}

// 源路徑(JAD-201):別名指向全主題簽入登入檔或按 usedThemeKeys 裁剪的源登入檔。
function buildImportedThemeRuntimeFromSource(outFile, usedThemeKeys = []) {
  const { registryPath, cleanup } = resolveThemeRegistryEntry(usedThemeKeys);
  try {
    buildClientRuntime({ root: ROOT, outFile, registryPath });
  } finally {
    cleanup();
  }
}

// 主題源是否在盤上(dev 倉為真;安裝版已刪 runtime.jsx + theme-registry.jsx,為假)。
function hasThemeSource(normalized) {
  if (!normalized.length) return fs.existsSync(FULL_THEME_REGISTRY);
  return normalized.every(key => fs.existsSync(path.join(ROOT, 'src/components/themes', key, 'runtime.jsx')));
}

function prebuiltModulesAvailable(normalized) {
  return normalized.length > 0 && normalized.every(key => fs.existsSync(prebuiltModulePath(ROOT, key)));
}

// 全主題(或主題集合無法識別時)→ 直接用簽入的全主題登入檔;
// 單/少主題 → 生成裁剪版臨時登入檔(寫到 gitignore 的 node_modules/.cache,
// import 用指向倉庫的絕對路徑,確保從臨時位置也能解析主題原始碼與 react)。
function resolveThemeRegistryEntry(usedThemeKeys) {
  const normalized = normalizeThemeKeys(usedThemeKeys || []);
  if (!normalized.length || isFullThemeSet(normalized)) {
    return { registryPath: FULL_THEME_REGISTRY, cleanup: () => {} };
  }
  const importPrefix = `${path.join(ROOT, 'src/components/themes')}/`;
  const source = buildThemeRegistrySource(normalized, { importPrefix });
  const cacheDir = path.join(ROOT, 'node_modules/.cache/dashi-theme-registry');
  fs.mkdirSync(cacheDir, { recursive: true });
  const registryPath = path.join(
    cacheDir,
    `registry-${process.pid}-${Date.now()}-${Math.random().toString(36).slice(2)}.jsx`,
  );
  fs.writeFileSync(registryPath, source);
  return {
    registryPath,
    cleanup: () => { try { fs.rmSync(registryPath, { force: true }); } catch {} },
  };
}

function copyImportedThemeAssets(outDir, usedThemeKeys = []) {
  const themesDir = path.join(ROOT, 'src/components/themes');
  if (!fs.existsSync(themesDir)) return;
  // JAD-201: a deck only needs its used theme(s)' assets. Empty/all-themes (e.g.
  // the showcase) copies everything; a single-/few-theme deck skips the rest,
  // shrinking the deck and not leaking other themes' image/video source assets.
  const usedFilter = new Set(usedThemeKeys || []);
  const copiedByRelativePath = new Map(
    REQUIRED_OUTPUT_ASSETS.map(assetPath => [
      assetPath,
      { themeKey: 'runtime', from: path.join(ROOT, assetPath) },
    ]),
  );
  for (const themeKey of fs.readdirSync(themesDir).sort()) {
    if (usedFilter.size > 0 && !usedFilter.has(themeKey)) continue;
    const sourceDir = path.join(themesDir, themeKey, 'source');
    if (!fs.existsSync(sourceDir)) continue;
    const files = [];
    collectThemeAssetFiles(sourceDir, files);
    files.forEach(from => {
      const rel = path.relative(sourceDir, from);
      const outputRel = rel.replaceAll(path.sep, '/');
      const existing = copiedByRelativePath.get(outputRel);
      if (existing) {
        throw new Error(`Theme asset output path collision: ${outputRel} (${existing.themeKey}: ${existing.from}, ${themeKey}: ${from})`);
      }
      copiedByRelativePath.set(outputRel, { themeKey, from });
      const to = path.join(outDir, rel);
      fs.mkdirSync(path.dirname(to), { recursive: true });
      fs.copyFileSync(from, to);
    });
  }
}

function collectThemeAssetFiles(dir, out) {
  for (const name of fs.readdirSync(dir).sort()) {
    const file = path.join(dir, name);
    const stat = fs.statSync(file);
    if (stat.isDirectory()) {
      if (MIGRATION_ONLY_DIRS.has(name.toLowerCase())) continue;
      collectThemeAssetFiles(file, out);
      continue;
    }
    if (/\.(png|jpe?g|webp|gif|svg|mp4|mov)$/i.test(name)) out.push(file);
  }
}

function copyDirectoryIfExists(from, to) {
  if (!fs.existsSync(from)) return;
  for (const name of fs.readdirSync(from)) {
    const source = path.join(from, name);
    const target = path.join(to, name);
    const stat = fs.statSync(source);
    if (stat.isDirectory()) {
      copyDirectoryIfExists(source, target);
    } else {
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.copyFileSync(source, target);
    }
  }
}

function copyFileIfExists(from, to) {
  if (fs.existsSync(from)) {
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.copyFileSync(from, to);
  }
}

// 交付件必需的 vendor 庫缺失時立刻失敗,不允許靜默產出缺指令碼的 deck。
function copyRequiredFile(from, to) {
  if (!fs.existsSync(from)) {
    throw new Error(`Required vendor asset missing: ${from}`);
  }
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(from, to);
}

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function escapeScriptJson(value) {
  return value
    .replaceAll('<', '\\u003c')
    .replaceAll('\u2028', '\\u2028')
    .replaceAll('\u2029', '\\u2029');
}
